name: Generate
on:
  push:
  pull_request:
jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build
        run: go run generate.go
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gh-pages
          path: gh-pages/*
          if-no-files-found: error
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: dist
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: gh-pages
          path: artifacts
      - name: Deploy
        run: |
          set -euo pipefail
          rsync -az --exclude=.git --delete ./artifacts/ ./dist/
          cd dist
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Publish"
            git push --set-upstream --force origin gh-pages
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}